-- Baseline. Domain tables arrive with the first feature slice.
--
-- pgcrypto gives us gen_random_uuid(). Ticket Codes are NOT generated here:
-- nfr.md requires 128 bits of cryptographic randomness generated by the
-- application and never derived from a database identifier.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Every domain table carries organization_id and has row-level security enabled
-- against it (ADR-0004). The application sets the tenant for each transaction.
